### ISSUE TITLE
Some ideas from one player

### ISSUE THREAD

**Issue by ghost** [TransparentLC/project-striker#1]
How about using the third party to scan the QR , log in and upload the game time or the highest score record to the back-end to record ranking or the num of register players. 😊

**Comment by TransparentLC** [comment]
Online score ranking is an interesting feature and has been implemented indeed in many arcade games. However I won't add it since a ranking table that only contains names and scores is really simple and fake data can be easily submitted as the game is open-source so everyone can find how the upload request is sent.

For shump games, saving replay files which contain player's operations and other data (player name, type, score, etc.) is a better idea. I may add the replay system in future.

**Comment by ghost** [comment]
It makes good sense, and the replay system is also a good idea that can help players make progress quickly. Thank you for your reply, I will close the issue. 😊

**Comment by TransparentLC** [comment]
Replay system added. Feel free to try it and report any bug if you have found one!
